version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/agent"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/ui"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      npm-minor-patch:
        update-types: ["minor", "patch"]
      npm-major:
        update-types: ["major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/agent"
      - "/ui"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    groups:
      docker-images:
        patterns:
          - "*"
